#!/bin/bash

# fase, uplink, management, team...

# Parametri presi da console
# OUTSIDE_INTERFACE=$1
# OUTSIDE_ADDRESS=$2

# MANAGEMENT_INTERFACE=$3
# MANAGEMENT=$4

maskaddresses[0]=11.11.11.11
maskaddresses[1]=22.22.22.22
maskaddresses[2]=33.33.33.33
maskaddresses[3]=44.44.44.44
maskaddresses[4]=55.55.55.55


MANAGEMENT_INTERFACE="ens37"

TEAM1_INTERFACE="ens38"
TEAM2_INTERFACE="ens39"
TEAM3_INTERFACE="ens40"


# Pulizia delle attuali regole e reset ad ACCEPT
sudo iptables -F
sudo iptables -P FORWARD ACCEPT
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -t nat -F

# DROP di tutti i pacchetti da inoltrare
sudo iptables -P FORWARD DROP

# DROP dei pacchetti da ricevere (incluso ping)
sudo iptables -P INPUT DROP


# Accetta tutte le connessioni dal management
sudo iptables -A INPUT -i $MANAGEMENT_INTERFACE -j ACCEPT
# Accetta tutte le connessioni da macchina host di vmware (per comodità)
sudo iptables -A INPUT -s 172.168.1.1 -j ACCEPT

# Permette ping da management a chiunque + risposta
# Non permette ping dalle squadre verso nessuno all’infuori del proprio subnet:
sudo iptables -A FORWARD -p icmp --icmp-type 8 -i $MANAGEMENT_INTERFACE -j ACCEPT
sudo iptables -A FORWARD -p icmp --icmp-type 0 -o $MANAGEMENT_INTERFACE -j ACCEPT

# Permette nuova connessione tcp solo da management, gli altri non possono iniziarla
sudo iptables -A FORWARD -p tcp -i $MANAGEMENT_INTERFACE -m state --state NEW -j ACCEPT
# sudo iptables -A FORWARD -p tcp -s 0/0 -d $MANAGEMENT -m state ! --state NEW -j ACCEPT
sudo iptables -A FORWARD -m conntrack --ctstate ESTABLISHED -j ACCEPT

# Non permettere alcun protocollo dalle sottoreti di gara all’interfaccia di management
# ciò avviene perché la politica di FORWARD è DROP



# SECONDA FASE

# permettere da management ad uplink, non viceversa
# drop pacchetti destinati ad uplink e management
# accept all sulla catena di forward

# Permette FORWARD di ogni connessione tra le squadre
sudo iptables -A FORWARD -i $TEAM1_INTERFACE -o $TEAM2_INTERFACE -j ACCEPT # provare a togliere -i e -o
sudo iptables -A FORWARD -i $TEAM1_INTERFACE -o $TEAM3_INTERFACE -j ACCEPT

sudo iptables -A FORWARD -i $TEAM2_INTERFACE -o $TEAM1_INTERFACE -j ACCEPT
sudo iptables -A FORWARD -i $TEAM2_INTERFACE -o $TEAM3_INTERFACE -j ACCEPT

sudo iptables -A FORWARD -i $TEAM3_INTERFACE -o $TEAM1_INTERFACE -j ACCEPT
sudo iptables -A FORWARD -i $TEAM3_INTERFACE -o $TEAM2_INTERFACE -j ACCEPT



# Cambia indirizzo sorgente dei TUTTI i pacchetti verso i team
# sudo iptables -t nat -A POSTROUTING -o $TEAM1_INTERFACE -j SNAT --to-source 11.11.11.11
# sudo iptables -t nat -A POSTROUTING -o $TEAM2_INTERFACE -j SNAT --to-source 22.22.22.22
# sudo iptables -t nat -A POSTROUTING -o $TEAM3_INTERFACE -j SNAT --to-source 33.33.33.33


# Cambia indirizzo sorgente dei TUTTI i pacchetti verso i team in modo randomico
sudo iptables -t nat -A POSTROUTING -o $TEAM1_INTERFACE -j SNAT --to-source ${maskaddresses[$[ $RANDOM % 5]]}
sudo iptables -t nat -A POSTROUTING -o $TEAM2_INTERFACE -j SNAT --to-source ${maskaddresses[$[ $RANDOM % 5]]}
sudo iptables -t nat -A POSTROUTING -o $TEAM3_INTERFACE -j SNAT --to-source ${maskaddresses[$[ $RANDOM % 5]]}



# Cambia l'indirizzo sorgente dei pacchetti proveniente dalla sottorete -s e indirizzati alla squadra 2
# iptables -t nat -A POSTROUTING -o $TEAM2_INTERFACE -s 172.168.3.0/24 -j SNAT --to-source 3.4.5.6


# DA TESTARE




# Permette connessione tcp dalla subnet del management
# sudo iptables -A INPUT -p tcp -s $MANAGEMENT --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT

# Permette traffico su connessioni stabilite e/o collegate tra loro
# sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
# sudo iptables -A OUTPUT -m conntrack --ctstate ESTABLISHED -j ACCEPT
