#!/bin/bash

# fase, uplink, management, team...

nteams=$(expr $# - 3)

phase=$1
# uplink=$2
# management=$3


# Parametri presi da console
# UPLINK=$1
# OUTSIDE_ADDRESS=$2

# MANAGEMENT_INTERFACE=$3
# MANAGEMENT=$4

maskaddresses[0]=11.11.11.11
maskaddresses[1]=22.22.22.22
maskaddresses[2]=33.33.33.33
maskaddresses[3]=44.44.44.44
maskaddresses[4]=55.55.55.55


MANAGEMENT_INTERFACE="ens37"

TEAM1_INTERFACE="ens38"
TEAM2_INTERFACE="ens39"
TEAM3_INTERFACE="ens40"

    

# Pulizia delle attuali regole e reset ad ACCEPT
sudo iptables -F
sudo iptables -P FORWARD ACCEPT
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -t nat -F


# DROP di tutti i pacchetti da inoltrare
sudo iptables -P FORWARD DROP

# DROP dei pacchetti da ricevere (incluso ping)
sudo iptables -P INPUT DROP


# Accetta tutte le connessioni dal management
sudo iptables -A INPUT -i $MANAGEMENT_INTERFACE -j ACCEPT
# Accetta tutte le connessioni da macchina host di vmware (per comodità)
sudo iptables -A INPUT -s 172.168.1.1 -j ACCEPT

# Permette ping da management a chiunque + risposta
# Non permette ping dalle squadre verso nessuno all’infuori del proprio subnet:
sudo iptables -A FORWARD -p icmp --icmp-type 8 -i $MANAGEMENT_INTERFACE -j ACCEPT
sudo iptables -A FORWARD -p icmp --icmp-type 0 -o $MANAGEMENT_INTERFACE -j ACCEPT

# Permette nuova connessione tcp solo da management, gli altri non possono iniziarla
sudo iptables -A FORWARD -p tcp -i $MANAGEMENT_INTERFACE -m state --state NEW -j ACCEPT
# sudo iptables -A FORWARD -p tcp -s 0/0 -d $MANAGEMENT -m state ! --state NEW -j ACCEPT
sudo iptables -A FORWARD -m conntrack --ctstate ESTABLISHED -j ACCEPT


# Permette connessioni loopback
sudo iptables -A INPUT -i lo -j ACCEPT
sudo iptables -A OUTPUT -o lo -j ACCEPT

# Permette le risposte al ping da parte di chiunque
sudo iptables -A INPUT -p icmp --icmp-type 0 -j ACCEPT


if [ $phase -eq 2 ]
then 

    # SECONDA FASE

    # permettere da management ad uplink, non viceversa
    sudo iptables -A FORWARD -i $MANAGEMENT_INTERFACE -j ACCEPT

    # drop pacchetti destinati ad uplink e management
    sudo iptables -A FORWARD -o uplink -j DROP
    sudo iptables -A FORWARD -o $MANAGEMENT_INTERFACE -j DROP

    # accept all sulla catena di forward
    sudo iptables -A FORWARD -j ACCEPT 

    # Cambia indirizzo sorgente dei TUTTI i pacchetti verso i team in modo randomico
    sudo iptables -t nat -A POSTROUTING -o $TEAM1_INTERFACE -j SNAT --to-source ${maskaddresses[$[ $RANDOM % 5]]}
    sudo iptables -t nat -A POSTROUTING -o $TEAM2_INTERFACE -j SNAT --to-source ${maskaddresses[$[ $RANDOM % 5]]}
    sudo iptables -t nat -A POSTROUTING -o $TEAM3_INTERFACE -j SNAT --to-source ${maskaddresses[$[ $RANDOM % 5]]}

fi
