#!/bin/bash

# fase, uplink, management, team...

# -p = phase [1 or 2]
# -u = uplink interface
# -m = management interface
# -r = masquerading mode [true for random addresses, false for no masquerading, set single or multiple (around "") IPs (for each team, in order)]
# -t = team n interface (around quotes "")

while getopts p:u:m:r:t: option
do
case "${option}"
in
p) PHASE=${OPTARG};;
u) UPLINK=${OPTARG};;
m) MANAGEMENT_INTERFACE=${OPTARG};;
r) MASQUERADING=(${OPTARG});; # LE PARENTESI SERVONO A TRASFORMARE LA STRINGA IN ARRAY
t) TEAMS=(${OPTARG});; #lista delle interfacce, in ordine
esac
done


# abilita connessione internet attraverso VRouter
sudo iptables -t nat -A POSTROUTING -o $UPLINK -j MASQUERADE
    

# Pulizia delle attuali regole e reset ad ACCEPT
sudo iptables -F
sudo iptables -P FORWARD ACCEPT
sudo iptables -P INPUT ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -t nat -F
sudo iptables -X LOGGING # elimina chain di LOGGING se esistente



# DROP di tutti i pacchetti da inoltrare
# sudo iptables -P FORWARD DROP

# DROP dei pacchetti da ricevere (incluso ping)
sudo iptables -P INPUT DROP

# Log di tutti i pacchetti entranti droppati
sudo iptables -N LOGGING # crea nuova chain
sudo iptables -A INPUT -j LOGGING # manda tutti i pacchetti entranti alla chain LOGGING
sudo iptables -A LOGGING -m limit --limit 1/min -j LOG --log-prefix "COMPETITION-LOG: " --log-level 4
# sudo iptables -A LOGGING -j DROP # i pacchetti arrivati in LOGGING saranno droppati

# ------------------------------------------------------------

# Accetta tutte le connessioni dal management
sudo iptables -A INPUT -i $MANAGEMENT_INTERFACE -j ACCEPT
# Accetta tutte le connessioni da macchina host di vmware (per comodità)
# usare interfaccia al posto di ip
sudo iptables -A INPUT -s 172.168.1.1 -j ACCEPT

# ------------------------------------------------------------

# Permette ping da management a chiunque + risposta
# SUPERFLUA? FORWARD ACCEPTS ALL
# sudo iptables -A FORWARD -p icmp --icmp-type 8 -i $MANAGEMENT_INTERFACE -j ACCEPT


# permette risposta al ping iniziato da management (SUPERFLUO? DATO CHE FORWARD PERMETTE TUTTO)
# sudo iptables -A FORWARD -p icmp --icmp-type 0 -o $MANAGEMENT_INTERFACE -j ACCEPT


# Permette nuova connessione tcp solo da management, gli altri non possono iniziarla (SUPERFLUO? FORWARD ACCEPTS ALL)
# sudo iptables -A FORWARD -p tcp -i $MANAGEMENT_INTERFACE -m state --state NEW -j ACCEPT




# Drop di tutti i pacchetti da inoltrare 
# ?????????????????????? si dovrebbero attivare le altre sopra
sudo iptables -A FORWARD -j DROP 

    # TODO: DA ABILITARE REGOLE SOPRA SE IMPOSTIAMO FORWARDA A DROP


# Permettere connessione nuova udp da management
# sudo iptables -A FORWARD -p udp -i $MANAGEMENT_INTERFACE -m state --state NEW -j ACCEPT



# Permette connessioni loopback
sudo iptables -A INPUT -i lo -j ACCEPT
# implicita
# sudo iptables -A OUTPUT -o lo -j ACCEPT

# Permette le risposte al ping iniziato dal virtual router da parte di chiunque
sudo iptables -A INPUT -p icmp --icmp-type 0 -j ACCEPT



if [ $PHASE -eq 2 ]
then 

    # SECONDA FASE

    # accept all sulla catena di forward
    sudo iptables -A FORWARD -j ACCEPT 
    
    # manda tutti i pacchetti alla chain LOGGING
    sudo iptables -A FORWARD -j LOGGING 

    # TODO: forse da mettere su
    # Permette di rispondere a connessioni già stabilite (ovviamente solo chi ha il permesso può iniziarle)
    sudo iptables -A FORWARD -m conntrack --ctstate ESTABLISHED -j ACCEPT # FUNZIONA ANCHE PER UDP, SENZA QUESTA UDP NON RICEVE ACK

    # importante tenerla altrimenti i pacchetti cadono nella regola successiva (di drop) e vengono scartati
    # permettere da management a chiunque, non viceversa
    sudo iptables -A FORWARD -i $MANAGEMENT_INTERFACE -j ACCEPT

    # drop pacchetti destinati ad uplink e management
    sudo iptables -A FORWARD -o $UPLINK -j DROP
    sudo iptables -A FORWARD -o $MANAGEMENT_INTERFACE -j DROP


    if [ ${#MASQUERADING[@]} -eq 1 ]
    then
        
        if [ $MASQUERADING = true ] # se scelto masquerading random
        then

            for interface in "${TEAMS[@]}"
            do
                sudo iptables -t nat -A POSTROUTING -o $interface -j SNAT --to-source $((RANDOM%253+1)).$((RANDOM%253+1)).$((RANDOM%253+1)).$((RANDOM%253+1))
            done

        elif [ $MASQUERADING != false ] # se impostato un indirizzo uguale per tutti 
        then
            for interface in "${TEAMS[@]}"
            do
                sudo iptables -t nat -A POSTROUTING -o $interface -j SNAT --to-source $MASQUERADING
            done
        fi
    elif [ ${#MASQUERADING[@]} > 1 ] # se impostato un indirizzo per ogni squadra
        then
            for ((i=0;i<${#TEAMS[@]};++i))
            do
                sudo iptables -t nat -A POSTROUTING -o ${TEAMS[i]} -j SNAT --to-source ${MASQUERADING[i]}
            done
    fi

fi
