network:
  ethernets:
    enp2s0f2:
      addresses: 172.168.3.100
    version: 2
    vmnet4:
      addresses: 172.168.4.100
    vmnet5:
      addresses: 172.168.5.100
    vmnet8:
      addresses: 172.168.6.100
